import { StyleSheet } from "react-native";
export const homeStyles = StyleSheet.create({
  homeContainer: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    flex: 1,
    paddingBottom: "10%",
  },
  homeContainerIos: {
    flexDirection: "column",
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  homeDirection: {
    flexDirection: "row",
  },
  fiatStyle: {
    fontFamily: "Mulish",
    fontWeight: "700",
    fontSize: 40,
    color: "#C0CCDA",
    lineHeight: 50,
    textAlign: "center",
    marginTop: 85,
  },
  fiatStyleValid: {
    fontFamily: "Mulish",
    fontWeight: "700",
    fontSize: 40,
    color: "#035AC5",
    lineHeight: 50,
    textAlign: "center",
    marginTop: 85,
  },
  fiatAmountInput: {
    maxWidth: 300,
    textAlign: "center",
    fontSize: 40,
    fontFamily: "Mulish",
    fontWeight: "700",
    color: "#C0CCDA",
    lineHeight: 50,
    marginTop: 85,
  },
  fiatAmountInputValid: {
    maxWidth: 300,
    textAlign: "center",
    fontSize: 40,
    fontFamily: "Mulish",
    fontWeight: "700",
    color: "#035AC5",
    lineHeight: 50,
    marginTop: 85,
  },
  conceptInputContainer: {
    flexDirection: "column",
    justifyContent: "center",
    marginVertical: 70,
    width: "90%",
  },
  subjectInput: {
    fontFamily: "Mulish",
    color: "#002859",
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 20,
    paddingVertical: 3,
  },
  conceptInput: {
    borderRadius: 6,
    paddingHorizontal: 18,
    paddingVertical: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: "#E5E9F2",
    maxHeight: 90,
    fontSize: 14,
    lineHeight: 20,
    color: "#002859",
    fontWeight: "500",
    fontFamily: "MulishMedium",
  },
  conceptInputFocused: {
    borderRadius: 6,
    paddingHorizontal: 18,
    paddingVertical: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: "#035AC5",
    maxHeight: 90,
    fontSize: 14,
    lineHeight: 20,
    color: "#002859",
    fontWeight: "500",
    fontFamily: "MulishMedium",
  },
  limitCharacters: { textAlign: "right", color: "#647184" },
  nonVisibleCharacters: { color: "#FFFFFF" },
  submitDisabled: {
    // marginTop: 50,
    paddingHorizontal: 24,
    paddingVertical: 18,
    width: "90%",
    flexDirection: "column",
    backgroundColor: "#EAF3FF",
    fontWeight: 600,
  },
  submitEnabled: {
    // marginTop: 50,
    paddingHorizontal: 24,
    paddingVertical: 18,
    width: "90%",
    flexDirection: "column",
    backgroundColor: "#035AC5",
  },
  buttonContentDisabled: {
    borderRadius: 15,
    fontFamily: "Mulish",
    textAlign: "center",
    color: "#71B0FD",
    fontSize: 16,
    fontWeight: "600",
  },
  buttonContentEnabled: {
    borderRadius: 15,
    fontFamily: "Mulish",
    textAlign: "center",
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});
