export const countriesData = [
  { id: 1, name: "Afghanistan", dialCode: "+93", code: "AF" },
  { id: 2, name: "Albania", dialCode: "+355", code: "AL" },
  { id: 3, name: "Algeria", dialCode: "+213", code: "DZ" },
  { id: 4, name: "American Samoa", dialCode: "+1-684", code: "AS" },
  { id: 5, name: "Andorra", dialCode: "+376", code: "AD" },
  { id: 6, name: "Angola", dialCode: "+244", code: "AO" },
  { id: 7, name: "Anguilla", dialCode: "+1-264", code: "AI" },
  { id: 8, name: "Antigua and Barbuda", dialCode: "+1-268", code: "AG" },
  { id: 9, name: "Argentina", dialCode: "+54", code: "AR" },
  { id: 10, name: "Armenia", dialCode: "+374", code: "AM" },
  { id: 11, name: "Aruba", dialCode: "+297", code: "AW" },
  { id: 12, name: "Australia", dialCode: "+61", code: "AU" },
  { id: 13, name: "Austria", dialCode: "+43", code: "AT" },
  { id: 14, name: "Azerbaijan", dialCode: "+994", code: "AZ" },
  { id: 15, name: "Bahamas", dialCode: "+1-242", code: "BS" },
  { id: 16, name: "Bahrain", dialCode: "+973", code: "BH" },
  { id: 17, name: "Bangladesh", dialCode: "+880", code: "BD" },
  { id: 18, name: "Barbados", dialCode: "+1-246", code: "BB" },
  { id: 19, name: "Belarus", dialCode: "+375", code: "BY" },
  { id: 20, name: "Belgium", dialCode: "+32", code: "BE" },
  { id: 21, name: "Belize", dialCode: "+501", code: "BZ" },
  { id: 22, name: "Benin", dialCode: "+229", code: "BJ" },
  { id: 23, name: "Bermuda", dialCode: "+1-441", code: "BM" },
  { id: 24, name: "Bhutan", dialCode: "+975", code: "BT" },
  { id: 25, name: "Bolivia", dialCode: "+591", code: "BO" },
  { id: 26, name: "Bosnia and Herzegovina", dialCode: "+387", code: "BA" },
  { id: 27, name: "Botswana", dialCode: "+267", code: "BW" },
  { id: 28, name: "Brazil", dialCode: "+55", code: "BR" },
  { id: 29, name: "British Virgin Islands", dialCode: "+1-284", code: "VG" },
  { id: 30, name: "Brunei", dialCode: "+673", code: "BN" },
  { id: 31, name: "Bulgaria", dialCode: "+359", code: "BG" },
  { id: 32, name: "Burkina Faso", dialCode: "+226", code: "BF" },
  { id: 33, name: "Burundi", dialCode: "+257", code: "BI" },
  { id: 34, name: "Cambodia", dialCode: "+855", code: "KH" },
  { id: 35, name: "Cameroon", dialCode: "+237", code: "CM" },
  { id: 36, name: "Canada", dialCode: "+1", code: "CA" },
  { id: 37, name: "Cape Verde", dialCode: "+238", code: "CV" },
  { id: 38, name: "Cayman Islands", dialCode: "+1-345", code: "KY" },
  { id: 39, name: "Central African Republic", dialCode: "+236", code: "CF" },
  { id: 40, name: "Chad", dialCode: "+235", code: "TD" },
  { id: 41, name: "Chile", dialCode: "+56", code: "CL" },
  { id: 42, name: "China", dialCode: "+86", code: "CN" },
  { id: 43, name: "Colombia", dialCode: "+57", code: "CO" },
  { id: 44, name: "Comoros", dialCode: "+269", code: "KM" },
  { id: 45, name: "Congo - Brazzaville", dialCode: "+242", code: "CG" },
  { id: 46, name: "Congo - Kinshasa", dialCode: "+243", code: "CD" },
  { id: 47, name: "Cook Islands", dialCode: "+682", code: "CK" },
  { id: 48, name: "Costa Rica", dialCode: "+506", code: "CR" },
  { id: 49, name: "Croatia", dialCode: "+385", code: "HR" },
  { id: 50, name: "Cuba", dialCode: "+53", code: "CU" },
  { id: 51, name: "Cyprus", dialCode: "+357", code: "CY" },
  { id: 52, name: "Czech Republic", dialCode: "+420", code: "CZ" },
  { id: 53, name: "Denmark", dialCode: "+45", code: "DK" },
  { id: 54, name: "Djibouti", dialCode: "+253", code: "DJ" },
  { id: 55, name: "Dominica", dialCode: "+1-767", code: "DM" },
  { id: 56, name: "Dominican Republic", dialCode: "+1-809", code: "DO" },
  { id: 57, name: "Dominican Republic", dialCode: "+1-829", code: "DO" },
  { id: 58, name: "Dominican Republic", dialCode: "+1-849", code: "DO" },
  { id: 59, name: "Ecuador", dialCode: "+593", code: "EC" },
  { id: 60, name: "Egypt", dialCode: "+20", code: "EG" },
  { id: 61, name: "El Salvador", dialCode: "+503", code: "SV" },
  { id: 62, name: "Equatorial Guinea", dialCode: "+240", code: "GQ" },
  { id: 63, name: "Eritrea", dialCode: "+291", code: "ER" },
  { id: 64, name: "Estonia", dialCode: "+372", code: "EE" },
  { id: 65, name: "Eswatini", dialCode: "+268", code: "SZ" },
  { id: 66, name: "Ethiopia", dialCode: "+251", code: "ET" },
  { id: 67, name: "Fiji", dialCode: "+679", code: "FJ" },
  { id: 68, name: "Finland", dialCode: "+358", code: "FI" },
  { id: 69, name: "France", dialCode: "+33", code: "FR" },
  { id: 70, name: "French Guiana", dialCode: "+594", code: "GF" },
  { id: 71, name: "French Polynesia", dialCode: "+689", code: "PF" },
  { id: 72, name: "Gabon", dialCode: "+241", code: "GA" },
  { id: 73, name: "Gambia", dialCode: "+220", code: "GM" },
  { id: 74, name: "Georgia", dialCode: "+995", code: "GE" },
  { id: 75, name: "Germany", dialCode: "+49", code: "DE" },
  { id: 76, name: "Ghana", dialCode: "+233", code: "GH" },
  { id: 77, name: "Gibraltar", dialCode: "+350", code: "GI" },
  { id: 78, name: "Greece", dialCode: "+30", code: "GR" },
  { id: 79, name: "Greenland", dialCode: "+299", code: "GL" },
  { id: 80, name: "Grenada", dialCode: "+1-473", code: "GD" },
  { id: 81, name: "Guadeloupe", dialCode: "+590", code: "GP" },
  { id: 82, name: "Guam", dialCode: "+1-671", code: "GU" },
  { id: 83, name: "Guatemala", dialCode: "+502", code: "GT" },
  { id: 84, name: "Guernsey", dialCode: "+44-1481", code: "GG" },
  { id: 85, name: "Guinea", dialCode: "+224", code: "GN" },
  { id: 86, name: "Guinea-Bissau", dialCode: "+245", code: "GW" },
  { id: 87, name: "Guyana", dialCode: "+592", code: "GY" },
  { id: 88, name: "Haiti", dialCode: "+509", code: "HT" },
  { id: 89, name: "Honduras", dialCode: "+504", code: "HN" },
  { id: 90, name: "Hong Kong", dialCode: "+852", code: "HK" },
  { id: 91, name: "Hungary", dialCode: "+36", code: "HU" },
  { id: 92, name: "Iceland", dialCode: "+354", code: "IS" },
  { id: 93, name: "India", dialCode: "+91", code: "IN" },
  { id: 94, name: "Indonesia", dialCode: "+62", code: "ID" },
  { id: 95, name: "Iran", dialCode: "+98", code: "IR" },
  { id: 96, name: "Iraq", dialCode: "+964", code: "IQ" },
  { id: 97, name: "Ireland", dialCode: "+353", code: "IE" },
  { id: 98, name: "Isle of Man", dialCode: "+44-1624", code: "IM" },
  { id: 99, name: "Israel", dialCode: "+972", code: "IL" },
  { id: 100, name: "Italy", dialCode: "+39", code: "IT" },
  { id: 101, name: "Jamaica", dialCode: "+1-876", code: "JM" },
  { id: 102, name: "Japan", dialCode: "+81", code: "JP" },
  { id: 103, name: "Jersey", dialCode: "+44-1534", code: "JE" },
  { id: 104, name: "Jordan", dialCode: "+962", code: "JO" },
  { id: 105, name: "Kazakhstan", dialCode: "+7", code: "KZ" },
  { id: 106, name: "Kenya", dialCode: "+254", code: "KE" },
  { id: 107, name: "Kiribati", dialCode: "+686", code: "KI" },
  { id: 108, name: "North Korea", dialCode: "+850", code: "KP" },
  { id: 109, name: "South Korea", dialCode: "+82", code: "KR" },
  { id: 110, name: "Kuwait", dialCode: "+965", code: "KW" },
  { id: 111, name: "Kyrgyzstan", dialCode: "+996", code: "KG" },
  { id: 112, name: "Laos", dialCode: "+856", code: "LA" },
  { id: 113, name: "Latvia", dialCode: "+371", code: "LV" },
  { id: 114, name: "Lebanon", dialCode: "+961", code: "LB" },
  { id: 115, name: "Lesotho", dialCode: "+266", code: "LS" },
  { id: 116, name: "Liberia", dialCode: "+231", code: "LR" },
  { id: 117, name: "Libya", dialCode: "+218", code: "LY" },
  { id: 118, name: "Liechtenstein", dialCode: "+423", code: "LI" },
  { id: 119, name: "Lithuania", dialCode: "+370", code: "LT" },
  { id: 120, name: "Luxembourg", dialCode: "+352", code: "LU" },
  { id: 121, name: "Macau", dialCode: "+853", code: "MO" },
  { id: 122, name: "Madagascar", dialCode: "+261", code: "MG" },
  { id: 123, name: "Malawi", dialCode: "+265", code: "MW" },
  { id: 124, name: "Malaysia", dialCode: "+60", code: "MY" },
  { id: 125, name: "Maldives", dialCode: "+960", code: "MV" },
  { id: 126, name: "Mali", dialCode: "+223", code: "ML" },
  { id: 127, name: "Malta", dialCode: "+356", code: "MT" },
  { id: 128, name: "Marshall Islands", dialCode: "+692", code: "MH" },
  { id: 129, name: "Martinique", dialCode: "+596", code: "MQ" },
  { id: 130, name: "Mauritania", dialCode: "+222", code: "MR" },
  { id: 131, name: "Mauritius", dialCode: "+230", code: "MU" },
  { id: 132, name: "Mayotte", dialCode: "+262", code: "YT" },
  { id: 133, name: "Mexico", dialCode: "+52", code: "MX" },
  { id: 134, name: "Micronesia", dialCode: "+691", code: "FM" },
  { id: 135, name: "Moldova", dialCode: "+373", code: "MD" },
  { id: 136, name: "Monaco", dialCode: "+377", code: "MC" },
  { id: 137, name: "Mongolia", dialCode: "+976", code: "MN" },
  { id: 138, name: "Montenegro", dialCode: "+382", code: "ME" },
  { id: 139, name: "Montserrat", dialCode: "+1-664", code: "MS" },
  { id: 140, name: "Morocco", dialCode: "+212", code: "MA" },
  { id: 141, name: "Mozambique", dialCode: "+258", code: "MZ" },
  { id: 142, name: "Myanmar", dialCode: "+95", code: "MM" },
  { id: 143, name: "Namibia", dialCode: "+264", code: "NA" },
  { id: 144, name: "Nauru", dialCode: "+674", code: "NR" },
  { id: 145, name: "Nepal", dialCode: "+977", code: "NP" },
  { id: 146, name: "Netherlands", dialCode: "+31", code: "NL" },
  { id: 147, name: "New Caledonia", dialCode: "+687", code: "NC" },
  { id: 148, name: "New Zealand", dialCode: "+64", code: "NZ" },
  { id: 149, name: "Nicaragua", dialCode: "+505", code: "NI" },
  { id: 150, name: "Niger", dialCode: "+227", code: "NE" },
  { id: 151, name: "Nigeria", dialCode: "+234", code: "NG" },
  { id: 152, name: "Niue", dialCode: "+683", code: "NU" },
  { id: 153, name: "Norfolk Island", dialCode: "+672", code: "NF" },
  { id: 154, name: "North Macedonia", dialCode: "+389", code: "MK" },
  { id: 155, name: "Northern Mariana Islands", dialCode: "+1-670", code: "MP" },
  { id: 156, name: "Norway", dialCode: "+47", code: "NO" },
  { id: 157, name: "Oman", dialCode: "+968", code: "OM" },
  { id: 158, name: "Pakistan", dialCode: "+92", code: "PK" },
  { id: 159, name: "Palau", dialCode: "+680", code: "PW" },
  { id: 160, name: "Palestine", dialCode: "+970", code: "PS" },
  { id: 161, name: "Panama", dialCode: "+507", code: "PA" },
  { id: 162, name: "Papua New Guinea", dialCode: "+675", code: "PG" },
  { id: 163, name: "Paraguay", dialCode: "+595", code: "PY" },
  { id: 164, name: "Peru", dialCode: "+51", code: "PE" },
  { id: 165, name: "Philippines", dialCode: "+63", code: "PH" },
  { id: 166, name: "Pitcairn Islands", dialCode: "+64", code: "PN" },
  { id: 167, name: "Poland", dialCode: "+48", code: "PL" },
  { id: 168, name: "Portugal", dialCode: "+351", code: "PT" },
  { id: 169, name: "Puerto Rico", dialCode: "+1-787", code: "PR" },
  { id: 170, name: "Qatar", dialCode: "+974", code: "QA" },
  { id: 171, name: "Republic of the Congo", dialCode: "+242", code: "CG" },
  { id: 172, name: "Reunion", dialCode: "+262", code: "RE" },
  { id: 173, name: "Romania", dialCode: "+40", code: "RO" },
  { id: 174, name: "Russia", dialCode: "+7", code: "RU" },
  { id: 175, name: "Rwanda", dialCode: "+250", code: "RW" },
  { id: 176, name: "Saint Barthelemy", dialCode: "+590", code: "BL" },
  { id: 177, name: "Saint Helena", dialCode: "+290", code: "SH" },
  { id: 178, name: "Saint Kitts and Nevis", dialCode: "+1-869", code: "KN" },
  { id: 179, name: "Saint Lucia", dialCode: "+1-758", code: "LC" },
  { id: 180, name: "Saint Martin", dialCode: "+590", code: "MF" },
  { id: 181, name: "Saint Pierre and Miquelon", dialCode: "+508", code: "PM" },
  {
    id: 182,
    name: "Saint Vincent and the Grenadines",
    dialCode: "+1-784",
    code: "VC",
  },
  { id: 183, name: "Samoa", dialCode: "+685", code: "WS" },
  { id: 184, name: "San Marino", dialCode: "+378", code: "SM" },
  { id: 185, name: "Sao Tome and Principe", dialCode: "+239", code: "ST" },
  { id: 186, name: "Saudi Arabia", dialCode: "+966", code: "SA" },
  { id: 187, name: "Senegal", dialCode: "+221", code: "SN" },
  { id: 188, name: "Serbia", dialCode: "+381", code: "RS" },
  { id: 189, name: "Seychelles", dialCode: "+248", code: "SC" },
  { id: 190, name: "Sierra Leone", dialCode: "+232", code: "SL" },
  { id: 191, name: "Singapore", dialCode: "+65", code: "SG" },
  { id: 192, name: "Sint Maarten", dialCode: "+1-721", code: "SX" },
  { id: 193, name: "Slovakia", dialCode: "+421", code: "SK" },
  { id: 194, name: "Slovenia", dialCode: "+386", code: "SI" },
  { id: 195, name: "Solomon Islands", dialCode: "+677", code: "SB" },
  { id: 196, name: "Somalia", dialCode: "+252", code: "SO" },
  { id: 197, name: "South Africa", dialCode: "+27", code: "ZA" },
  { id: 198, name: "South Sudan", dialCode: "+211", code: "SS" },
  { id: 199, name: "Spain", dialCode: "+34", code: "ES" },
  { id: 200, name: "Sri Lanka", dialCode: "+94", code: "LK" },
  { id: 201, name: "Sudan", dialCode: "+249", code: "SD" },
  { id: 202, name: "Suriname", dialCode: "+597", code: "SR" },
  { id: 203, name: "Svalbard and Jan Mayen", dialCode: "+47", code: "SJ" },
  { id: 204, name: "Sweden", dialCode: "+46", code: "SE" },
  { id: 205, name: "Switzerland", dialCode: "+41", code: "CH" },
  { id: 206, name: "Syria", dialCode: "+963", code: "SY" },
  { id: 207, name: "Taiwan", dialCode: "+886", code: "TW" },
  { id: 208, name: "Tajikistan", dialCode: "+992", code: "TJ" },
  { id: 209, name: "Tanzania", dialCode: "+255", code: "TZ" },
  { id: 210, name: "Thailand", dialCode: "+66", code: "TH" },
  { id: 211, name: "Timor-Leste", dialCode: "+670", code: "TL" },
  { id: 212, name: "Togo", dialCode: "+228", code: "TG" },
  { id: 213, name: "Tokelau", dialCode: "+690", code: "TK" },
  { id: 214, name: "Tonga", dialCode: "+676", code: "TO" },
  { id: 215, name: "Trinidad and Tobago", dialCode: "+1-868", code: "TT" },
  { id: 216, name: "Tunisia", dialCode: "+216", code: "TN" },
  { id: 217, name: "Turkey", dialCode: "+90", code: "TR" },
  { id: 218, name: "Turkmenistan", dialCode: "+993", code: "TM" },
  { id: 219, name: "Tuvalu", dialCode: "+688", code: "TV" },
  { id: 220, name: "Uganda", dialCode: "+256", code: "UG" },
  { id: 221, name: "Ukraine", dialCode: "+380", code: "UA" },
  { id: 222, name: "United Arab Emirates", dialCode: "+971", code: "AE" },
  { id: 223, name: "United Kingdom", dialCode: "+44", code: "GB" },
  { id: 224, name: "United States", dialCode: "+1", code: "US" },
  { id: 225, name: "Uruguay", dialCode: "+598", code: "UY" },
  { id: 226, name: "Uzbekistan", dialCode: "+998", code: "UZ" },
  { id: 227, name: "Vanuatu", dialCode: "+678", code: "VU" },
  { id: 228, name: "Vatican City", dialCode: "+39-06", code: "VA" },
  { id: 229, name: "Venezuela", dialCode: "+58", code: "VE" },
  { id: 230, name: "Vietnam", dialCode: "+84", code: "VN" },
  { id: 231, name: "Wallis and Futuna", dialCode: "+681", code: "WF" },
  { id: 232, name: "Western Sahara", dialCode: "+212", code: "EH" },
  { id: 233, name: "Yemen", dialCode: "+967", code: "YE" },
  { id: 234, name: "Zambia", dialCode: "+260", code: "ZM" },
  { id: 235, name: "Zimbabwe", dialCode: "+263", code: "ZW" },
];
